### ISSUE TITLE
Глючит заголовок таблицы в гриде

### ISSUE THREAD

**Issue by f213** [shogodev/argilla#172]
На длинных таблицах, при наличии горизонтального скролла, при попытке прокрутить вниз сдвинутую направо табличку уезжает заголовок. ![](https://cloud.githubusercontent.com/assets/1592663/3731519/b55242d6-16ec-11e4-9f32-2543c14145b9.png)

**Comment by tatarinov** [comment]
Не удалось воспроизвести ни в chrome, ни в firefox, но в opera.
![116216175434-backend-product-mozilla-firefox](https://cloud.githubusercontent.com/assets/3611790/13816687/d33da46a-eba8-11e5-88c0-4c4010bfa17f.png)
