### ISSUE TITLE
Нестандартное поведение скриптов в бекенде

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#198]
На первый взгляд или не все скрипты загружаются или стили в бекенде...

1) в инфостраницах, в дереве - для `ul #tree_BInfo` потеряли класс treeview (фото ниже)
![9zsljkxucey](https://cloud.githubusercontent.com/assets/11833113/13470048/f6f11f0a-e0cb-11e5-95dc-c6e90258f31b.jpg)

2) на форме редактирования меню не открывается popup для создания custom item

**Comment by FajeSu** [comment]
Баг появился после коммита ea41a57d399e9777087a6ba32d3b599e0e31e16d от 05.02.2016 15:14:06 (слияние с гитхабом)
Здесь, на гитхабе, отображаются изменения в 5 файлах. А при просмотре журнала в TortoiseGit показаны изменения в 106 файлах...

![argilla](https://cloud.githubusercontent.com/assets/11833113/13594059/17b9ea40-e523-11e5-8d35-219eb472fcac.png)

**Comment by tatarinov** [comment]
Баг появился в коммите 0960cc9540951664c9e9d29d213754c07c0b13b5. Поправили.
