### ISSUE TITLE
ViewHelper::getClearPhone()

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#199]
В строке [#137](https://github.com/shogodev/argilla/blob/master/protected/share/helpers/ViewHelper.php#L137) предполагается проверка длины строки? Тогда, у телефона с 8-кой впереди - 11 цифр.
```
if( strlen($clearPhone) == 11 ) {
  if( $clearPhone[0] == 8 )
    $clearPhone = '7'.ltrim($clearPhone, '8');

  $clearPhone = '+'.$clearPhone;
}
```

**Comment by tatarinov** [comment]
Спасибо.
