### ISSUE TITLE
Добавить поле "позиция" в модуль "Редиректы"

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#201]
И делать сортировку по нему. Наверное, так - после строки [#98](https://github.com/shogodev/argilla/blob/master/protected/components/redirect/RequestRedirectComponent.php#L98) добавить
`$this->criteria->order = 'position, id';`

**Comment by tatarinov** [comment]
Зачем?

**Comment by FajeSu** [comment]
Чтобы понизить приоритет у ранее созданных редиректов с исходными урлами меньшей вложенности.
Допустим, есть редиректы:
(id) 1 - `/root_1/child_1/` - `/new_root_1/`
(id) 2 - `/root_1/child_1/child_2/` - `/new_root_2/`

При переходе по адресу `/root_1/child_1/child_2/` будет произведен редирект на страницу `/new_root_1/child_2/`, а не на `/new_root_2/`
Вот, чтобы не удалять первую запись и не создавать её после всех других, легче указывать позицию

**Comment by tatarinov** [comment]
Можно реализовать сортировку по длине урлов. Сначала обрабатывать длинные,  а потом более   короткие. Тогда в ручную можно будет позицию не проставлять.

**Comment by FajeSu** [comment]
Да, наверное, так лучше :-)
