### ISSUE TITLE
Не работает dropDown в гриде баннеров

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#204]
![untitled-1](https://cloud.githubusercontent.com/assets/11833113/13776294/1bc4da84-eacb-11e5-901d-104503234eeb.png)

**Comment by tatarinov** [comment]
Уже исправлено в 72ada04bbfe64f576167691d288b72f079c30fa8

**Comment by FajeSu** [comment]
Не, я думал новая какая-то ошибка, оказывается неправильно репозиторий склонировался
