### ISSUE TITLE
Жёстко заданные пути в некоторых файлах

### ISSUE THREAD

**Issue by schors** [shogodev/argilla#206]
В нескольких файлах жёстко заданы пути к фреймворку. Невозможно задать путь в одном месте, чтобы не перезаписывался после слияния. Из-за этого сложно поддерживать в некоторых окружениях.

В файле protected/yiic.php:
```
$yiic = dirname(__FILE__).'/../../yii/framework/yiic.php';
```

В файле index.php:
```
require_once(realpath(__DIR__.'/../yii/framework/'.$yii));
```

В файле backend/index.php:
```
require_once(realpath(__DIR__.'/../../yii/framework/yii.php'));
```

Они всё равно все лезут в кофиг какой-нибудь. Надо сделать специальный конфиг, который позволяет задать путь и не будет перезаписан при обновлении.

**Comment by tatarinov** [comment]
Я думаю, это можно будет реализовать. Может быть даже сделать класс вроде GlobalConfig, из которого можно будет получить путь к фреймворку, к фронтенду, к бэкэнду, может еще что. Этот класс будет инициализироваться в global_config.php. А это класс подключим в yiic.php, index.php, backend/index.php. 
Пока в приоритете другие задачи, но я думаю это тоже скоро реализуем.

**Comment by schors** [comment]
Ну вот я как хостер всегда становлюсь грустной пандой :)

**Comment by tatarinov** [comment]
Теперь путь к фреймворку можно задать в /protected/config/framework.php
