### ISSUE TITLE
Ошибка валидации скопированого продукта

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#207]
В бекенде у скопированного продукта не отображаются поля "Раздел", "Тип", "Категория" и при сохранении выдается ошибка валидации

**Comment by tatarinov** [comment]
Копирование товары воспринимались как модификации (товары производные от родительских)  из-за неправильной проверки в контролере. Баг поправили. 
При копирование товаров некоторые уникальные обязательные поля сбрасываются, ошибка валидации могла появятся из-за этого.
