### ISSUE TITLE
Ошибка загрузки конфигов

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#208]
Файл `/index.php`

Строка 7:
```
- $production = $globalConfig->frontendPath.'/production.php';
+ $production = $globalConfig->frontendConfigPath.'/production.php';
```

Строка 20:
```
- $config = $globalConfig->frontendConfigPath.'/frontend.php';
+ $config = require_once $globalConfig->frontendConfigPath.'/frontend.php';
```
---
В файле `/js/src/vendor/jquery_ui_widgets/jquery.ui.filterslider.js` в строке 18 должна ли быть запятая?

**Comment by tatarinov** [comment]
Спасибо.

**Comment by FajeSu** [comment]
А [20-ю](https://github.com/shogodev/argilla/blob/c5bb663de838348311f156de51a979db991481bd/index.php#L20) строку-то не поправили...
В любом режиме, YII_DEBUG = false
