### ISSUE TITLE
В бекенде не работает изменение позиции элемента меню

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#210]
В файле
`/protected/extensions/onflyedit/OnFlyEditField.php`
в строке [128](https://github.com/shogodev/argilla/blob/master/protected/extensions/onflyedit/OnFlyEditField.php#L128) сейчас указывается поле `position`, а нужно получать класс элемента меню, как это происходило раньше в файле
`/protected/modules/menu/components/grid/BFrontendMenuGridPositionColumn.php`
в строке [39](https://github.com/shogodev/argilla/blob/master/backend/protected/modules/menu/components/grid/BFrontendMenuGridPositionColumn.php#L39)

Может надо так написать?
```
'attribute' => get_class($data['model']),
```

И в файле
`/protected/modules/menu/components/grid/BFrontendMenuGridPositionColumn.php`
метод `prepareFieldData()` вообще удалить, раз он не используется?

**Comment by FajeSu** [comment]
скорее всего вот так
```
if( $data instanceof BActiveRecord ) {
  $primaryKey = $data->getPrimaryKey();
  $attribute = $this->name;
} else {
  $primaryKey = $data['id'];
  $attribute = get_class($data['model']);
}

Yii::app()->controller->widget('OnFlyWidget', array(
  'type' => empty($this->dropDown) ? OnFlyWidget::TYPE_INPUT : OnFlyWidget::TYPE_DROPDOWN,
  'ajaxUrl' => $this->ajaxUrl,
  'attribute' => $attribute,
  'primaryKey' => $primaryKey,
  'value' => $data[$this->name],
  'items' => $this->dropDown,
  'htmlOptions' => $htmlOptions
));
```

**Comment by tatarinov** [comment]
Исправлено в https://github.com/shogodev/argilla/commit/0b541d8c2d855b500c70af346282f740bee84d02
