### ISSUE TITLE
Вопрос по модификациям

### ISSUE THREAD

**Issue by FajeSu** [shogodev/argilla#216]
Как правильно работать с модификациями продукта?

При добавлении новой модификации происходит ошибка отсутствия атрибута `default_modification`, нужно ли добавить это поле в таблицу `{{product}}` или это делается через параметры?
Ради эксперимента добавил поле...

Метод `BModificationBehavior::getParentModel()` отдает `null`, потому что геттер доходит до метода `CActiveRecord::getRelated()` и в строке `265` отдает `null`
```
$relation=$md->relations[$name];
if($this->getIsNewRecord() && !$refresh && ($relation instanceof CHasOneRelation || $relation instanceof CHasManyRelation))
  return $relation instanceof CHasOneRelation ? null : array();
```

**Comment by tatarinov** [comment]
Для работы модификации поле default_modification не требуется. Код использующий default_modification попал в аргилу случайно. Он использовался для реализации специфической seo задачи, на одном проекте.

Из BModificationBehavior нужно удалить код:

```
    //to do: добавить параметр блокирующей отключение одного значения
    $this->owner->attachBehavior('radioToggleBehavior', array(
      'class' => 'RadioToggleBehavior',
      'conditionAttribute' => 'parent',
      'toggleAttribute' => 'default_modification'
    ));

    $this->owner->enableBehavior('radioToggleBehavior');
```

**Comment by FajeSu** [comment]
Хорошо, спасибо.

А что со вторым вопросом?
Это при создании модификации:
![img-2016-09-15-12-31-50](https://cloud.githubusercontent.com/assets/11833113/18541726/76ad919c-7b40-11e6-9552-986dc15d1451.png)

**Comment by tatarinov** [comment]
Обновите BModificationBehavior
