### ISSUE TITLE
FixAccessRights и assets

### ISSUE THREAD

**Issue by f213** [shogodev/argilla#38]
melnikov@boojaka:html$ phing fixAccessRights
    Buildfile: /usr/www/kalenji-melnikov/html/build.xml

    shogocms > fixAccessRights:

        [phing] Calling Buildfile '/usr/www/kalenji-melnikov/html/build/chmod.xml' with target ''

    shogocms_fixAccessRights > fixAccessRights:

        [phing] FileSystem::chmod() FAILED. Cannot chmod ./assets/61f152f17e7a290c081e59edffc106cd/css/bootstrap-responsive.css. Mode 664.

    BUILD FINISHED

    Total time: 1.7495 second

FixAccessRights не должен ходить в assets вообще, там права правильные сами по себе.

**Comment by tatarinov** [comment]
Пусть ходит в assets. Запускать нужно с sudo
